name: Build

on:
  push:
    branches:
      - main
      - develop/**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: swift build
      - run: swift test
